name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: sast-scan
      uses: AppThreat/sast-scan-action@master
      with:
        type: "java"

    - uses: actions/upload-artifact@v1
      with:
        name: reports
        path: reports
      
